name = "cloudflare-docs-ja"
type = "webpack"
account_id = "cd3f769b533ddce3ba2d5a0041509950"
workers_dev = true

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950"
zone_id = "351cf9fc660523187714fa772ad5ca49" # TODO
route = "https://developers.cloudflare.com/*" # TODO
kv_namespaces = [
    { binding = "REDIRECTS", id = "42719e2c4502479e9145f347015e5b34" }
]

[site]
bucket = "./public"
entry-point = "workers-site"
