name = "dns"
type = "webpack"
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev
workers_dev = true

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/dns*"

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
