name = "http3"
type = "webpack"
workers_dev = true
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/http3*"
kv_namespaces = [
    { binding = "REDIRECTS", id = "dd91f8b73f5843b8b67d91df7ff3a613" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
