name = "images"
type = "webpack"
workers_dev = true
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def" # cloudflare-docs.workers.dev
# Opt into backwards-incompatible changes through September 17, 2021.
compatibility_date = "2021-09-17"

[env.production]
workers_dev = false
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/images*"
kv_namespaces = [{ binding = "REDIRECTS", id = "0821ddd66f4742bdbbb56593b8b43fd8", preview_id = "0821ddd66f4742bdbbb56593b8b43fd8" }]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
