name = "page-shield"
type = "webpack"
workers_dev = true
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/page-shield*"
kv_namespaces = [
    { binding = "REDIRECTS", id = "5d7108a019fa4a929d70ffc6e9fb671d" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
