name = "pages"
type = "webpack"
workers_dev = true
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/pages*"
kv_namespaces = [
    { binding = "REDIRECTS", id = "153263ecbd3a436caf8c685ff3e26b93" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
