name = "byoip"
type = "webpack"
workers_dev = true
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/byoip*"
kv_namespaces = [{ binding = "REDIRECTS", id = "327898e0657e4e609149720d0353b652", preview_id = "327898e0657e4e609149720d0353b652" }]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
