name = "api-shield"
type = "webpack"
workers_dev = true
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/api-shield*"

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
