name = "warp-client"
type = "webpack"
workers_dev = true
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/warp-client*"
kv_namespaces = [
  { binding = "REDIRECTS", id = "f28bd6bb32a84aa0b4827c5dc2466bc1" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
