name = "workers"
type = "webpack"
workers_dev = true
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def" # cloudflare-docs.workers.dev
kv-namespaces = [{ binding = "REDIRECTS", id = "af84bea1a42641818938c15555f9cfa7", preview_id = "af84bea1a42641818938c15555f9cfa7" }] # `workers-docs-REDIRECTS_DEV` in dash

[env.production]
workers_dev = false
account_id = "0b3bd5b90e1a2cb2f45e2f1368546def" # cloudflare-docs.workers.dev
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/workers*"
kv-namespaces = [{ binding = "REDIRECTS", id = "18460178b7c6458b9dd4f6b99b27d2b1", preview_id = "18460178b7c6458b9dd4f6b99b27d2b1" }] # `workers-docs-REDIRECTS` in dash

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
