name = "firewall"
type = "webpack"
workers_dev = true
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev
# Opt into backwards-incompatible changes through September 17, 2021.
compatibility_date = "2021-09-17"

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/firewall*"
kv_namespaces = [
    { binding = "REDIRECTS", id = "6405ea2c8e794feca7b5dfcc5e53875a" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
