name = "email-routing"
type = "webpack"
account_id = "cd3f769b533ddce3ba2d5a0041509950" # cloudflare-docs.workers.dev
workers_dev = true
# Opt into backwards-incompatible changes through September 17, 2021.
compatibility_date = "2021-09-17"

[env.production]
workers_dev = false
account_id = "cd3f769b533ddce3ba2d5a0041509950"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/email-routing*"

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
